## USB Serial Logging
CONFIG_ZMK_USB_LOGGING=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

## PMW3610 Driver (ALT)
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_THREAD_STACK_SIZE=2048
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=2000
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=0
CONFIG_PMW3610_ALT_SMART_ALGORITHM=n