CONFIG_ZMK_USB_LOGGING=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_PMW3610_LOG_LEVEL_DBG=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

## Nordic SPI DMA Buffer Configuration
CONFIG_SPI_NRFX=y
CONFIG_SPI_ASYNC=n
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=32

## PMW3610 Driver
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_THREAD_STACK_SIZE=2048
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y