## Bluetooth
## https://zmk.dev/docs/troubleshooting/connection-issues#unreliableweak-connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

## Power Management Config
## https://zmk.dev/docs/config/power
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_PM_DEVICE=y

## Battery Level
## https://zmk.dev/docs/config/battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

## Pointing Subsystem (Modern ZMK)
## https://zmk.dev/docs/keymaps/behaviors/mouse-emulation
CONFIG_ZMK_POINTING=y

## Input Subsystem
CONFIG_INPUT=y

## Macros behavior queue
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

## Disable passkey entry for easier pairing
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_USB_LOGGING=y
