## Nordic SPI DMA Buffer Configuration
CONFIG_SPI_NRFX=y
CONFIG_SPI_ASYNC=n
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=32

## PMW3610 Driver
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_THREAD_STACK_SIZE=2048
CONFIG_ZMK_POINTING=y